version: '3.1'
services:
  main-service:
    build: main-service
    container_name: Main_Service
    depends_on:
      - main-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_MAIN=jdbc:postgresql://main-db:5432/ElectronicDiary
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ElectronicDiary
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  main-db:
    image: postgres:14-alpine
    container_name: Main_Service_Db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/dataMain

    environment:
      - POSTGRES_DB=ElectronicDiary
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  notification-service:
    build: notification-service
    container_name: Notification_Service
    ports:
      - "9090:9090"
    environment:
      - NOTIFICATION_SERVICE_URL=http://notification-service:9090

  report-service:
    build: report-service
    container_name: Report-Service
    ports:
      - "7070:7070"
    environment:
      - URL_REPORT_SERVICE=http://report-service:7070